In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots
import numpy as np

In [28]:
acao = yf.download("PETR3.SA")

acao = acao.drop(["Open","Close","Adj Close","Volume"],axis="columns")

acao["Lucro"] = acao["High"] - acao["Low"]

acao["Taxa retorno"] = np.log(acao["Low"],acao["Lucro"])

[*********************100%***********************]  1 of 1 completed

In [36]:
acao["2022-10":"2022-11"].tail(20)

                                High        Low     Lucro  Taxa retorno
Date
2022-10-06 00:00:00-03:00  37.730000  36.599998  3.600048      3.600048
2022-10-07 00:00:00-03:00  38.410000  37.189999  3.616040      3.616040
2022-10-10 00:00:00-03:00  37.810001  36.880001  3.607669      3.607669
2022-10-11 00:00:00-03:00  37.279999  36.299999  3.591818      3.591818
2022-10-13 00:00:00-03:00  38.520000  36.090000  3.586016      3.586016
2022-10-14 00:00:00-03:00  37.919998  37.099998  3.613617      3.613617
2022-10-17 00:00:00-03:00  37.599998  36.459999  3.596216      3.596216
2022-10-18 00:00:00-03:00  37.740002  36.650002  3.601413      3.601413
2022-10-19 00:00:00-03:00  39.279999  37.660000  3.628599      3.628599
2022-10-20 00:00:00-03:00  40.290001  39.430000  3.674527      3.674527
2022-10-21 00:00:00-03:00  42.080002  40.130001  3.692124      3.692124
2022-10-24 00:00:00-03:00  40.619999  37.360001  3.620601      3.620601
2022-10-25 00:00:00-03:00  37.720001  36.520000  3.597860      3.597860
2022-10-26 00:00:00-03:00  36.930000  35.189999  3.560762      3.560762
2022-10-27 00:00:00-03:00  36.880001  35.990002  3.583241      3.583241
2022-10-28 00:00:00-03:00  36.220001  35.240002  3.562182      3.562182
2022-10-31 00:00:00-03:00  34.639999  32.520000  3.481855      3.481855
2022-11-01 00:00:00-03:00  33.900002  33.080002  3.498929      3.498929
2022-11-03 00:00:00-03:00  33.849998  32.720001  3.487987      3.487987
2022-11-04 00:00:00-03:00  34.330002  32.230000  3.472898      3.472898

In [3]:
df_itau = pd.DataFrame(acao["2000-01":])

df_itau.reset_index(inplace=True)